apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  selector:
    matchLabels:
      app: green
  replicas: 3
  template:
    metadata:
      labels:
        app: green
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "disk2"
                operator: In
                values: ["ssd"]
      containers:
      - name: green
        image: maheshckarumanchi/k8s
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http-server
          containerPort: 80